# Тестовая автоматизация.
# для передачи в SmartTherm комнатной температуры из
# вспомогательного числового объекта
#
# Передача значения вспомогательного числового объекта testN
# в number.NAME_t_indoor
#
# 1. Создаем testN:  Настройки->Устройства и службы->(Вверху) Вспомогательные ->
# (кнопка внизу) "+Создать вспомогательный объект) ->(Выбираем из списка)Число ->
# Название = testN, Минимальное значение -50, Максимальное значение 50,
# режим отображения - слайдер, шаг слайлера 0.1; нажимаем "Создать"
# Выводим слайдер с testN на панель: Обзор ->редактировать->Добавить карточк->
# Объекты ->(Выбрать из списка)testN/input_number.testn ->Сохранить
#
# 2. Создаем автоматизацию:
# Настройки->Автоматизации и сцены->Автоматизации->Создать автоматизацию->текстовый редактор
# для SmartTherm (v 0.7.5 - v 0.8) требуется ввести идентификатор объекта с именем
# NAME из настроек в вебинтерфейсе + в настройках PID
# указать "Источник температуры в комнате:" 3
# NAME в объектах HA будет маленькими (строчными) буквами
# Например:
# * в SmartTherm имя устройства задали "Boiler"
# * В HA в списке объектов появляется объект с именем "Boiler T indoor"
#   и идентификатором "number.boiler_t_indoor",
#   тогда в target_entity пишем так:
#    target_entity: number.boiler_t_indoor
#
# 3. Наблюдаем изменения T indoor:
# Настройки->Устройства и службы->MQTT->Устройства->Выбрать ваше устройство NAME
# ->Панель "Управление" ->T indoor -> смотрим график
# (в другой закладке браузера)Обзор->Слайдер testN из п.1.
# крутим слайдер и смотрим как меняется график
#
# Работает на
# Core 2024.11.2
# Supervisor 2024.11.2
# Operating System 13.2
# Пользовательский интерфейс 20241106.2

alias: TestTest Tindoor
description: ""
triggers:
  - trigger: time_pattern
    seconds: /10
conditions: []
actions:
  - variables:
      source_entity: input_number.testn
      target_entity: number.NAME_t_indoor
  - if: []
    then:
      - action: number.set_value
        metadata: {}
        data:
          value: "{{ states(source_entity)|float(0)|round(2) }}"
        target:
          entity_id: "{{ target_entity }}"
mode: single
